version: "3.9"
services:
  api-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookstore_api
    ports:
      - "5456:5432"
    volumes:
      - database_book_api:/var/lib/postgresql/data

volumes:
  database_book_api:

